### ISSUE TITLE
Mapa Mental de Conjuntos Lennin Gómez Sanchez A1S

### ISSUE THREAD

**Issue by LenninGS-0** [SistemasTecTlaxiaco/actividad-4-mapa-mental-LenninGS-0#2]
[Mapa Mental Conjuntos Lennin Gomez Sanchez A1S .pdf](https://github.com/user-attachments/files/17108693/Mapa.Mental.Conjuntos.Lennin.Gomez.Sanchez.A1S.pdf)

**Comment by Victor-noe12** [comment]
Manejo conceptual y dominio del tema 25/25
Relación entre los conceptos incluidos en el mapa 25/25
Calidad de la presentación 25/25
Jerarquía 25/25
CALIFICACION: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
